package dlm;

/*
 * Problem 2 - Project Euler
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *										1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

/**
 * @author David McEwen
 *
 * @returns Answer to #2
 */
public class Two {

	public static int fibonacci(int n)  {
	   if(n <= 1)	{
		   return n;
	   }
	   else	{
	       return fibonacci(n - 1) + fibonacci(n - 2);
	   }
	}
	
	public static void main(String[] args) {
		
		int i = 2;
		int sum = 0;
		while (fibonacci(i) < 4000000)	{
			if (fibonacci(i) % 2 == 0)	{
				sum += fibonacci(i);
			}
			i++;
		}
		System.out.println("Sum = " + sum);
	}
}
